# -*- coding: utf-8 -*-
"""
Created on Tue Apr  7 15:59:12 2026

@author: Lucas.Beem
"""


edd_compound = {'1,1-DICHLOROETHANE' : '1,1-Dichloroethane',
                '1,1-DICHLOROETHENE' : '1,1-Dichloroethene',
                '1,1-DICHLOROETHYLENE' : '1,1-Dichloroethylene',
                '1,1-DICHLOROPROPENE' : '1,1-Dichloropropene',
                '1,1,1-TRICHLOROETHANE' : '1,1,1-Trichloroethane',
                '1,1,1,2-TETRACHLOROETHANE' : '1,1,1,2-Tetrachloroethane',
                '1,1,2-TRICHLOROETHANE' : '1,1,2-Trichloroethane',
                '1,1,2,2-TETRACHLOROETHANE' : '1,1,2,2-Tetrachloroethane',
                '1,2-DIBROMO-3-CHLOROPROPANE' : '1,2-Dibromo-3-Chloropropane',
                '1,2-DIBROMOETHANE' : '1,2-Dibromoethane',
                '1,2-DICHLOROBENZENE' : '1,2-Dichlorobenzene',
                '1,2-DICHLOROETHANE' : '1,2-Dichloroethane',
                '1,2-DICHLOROETHENE (TOTAL)' : '1,2-Dichloroethene',
                '1,2-DICHLOROPROPANE' : '1,2-Dichloropropane',
                '1,2,3-TRICHLOROBENZENE' : '1,2,3-Trichlorobenzene',
                '1,2,3-TRICHLOROPROPANE' : '1,2,3-Trichloropropane',
                '1,2,4-TRICHLOROBENZENE' : '1,2,4-Trichlorobenzene',
                '1,2,4-TRIMETHYLBENZENE' : '1,2,4-Trimethylbenzene',
                '1,2,4,5-TETRAMETHYLBENZENE' : '1,2,4,5-Tetramethylbenzene',
                '1,3-DICHLOROBENZENE' : '1,3-Dichlorobenzene',
                '1,3-DICHLOROPROPENE, TOTAL' : '1,3-Dichloropropane',
                '1,3-DICHLOROPROPANE' : '1,3-Dichloropropane',
                '1,3,5-TRIMETHYLBENZENE' : '1,3,5-Trimethylbenzene',
                '1,4-DICHLOROBENZENE' : '1,4-Dichlorobenzene',
                '1,4-DICHLOROBUTANE' : '1,4-Dichlorobutane',
                '2-BUTANONE' : '2-Butanone',
                '2-BUTANONE (MEK)': '2-Butanone',
                '2-CHLOROTOLUENE' : '2-Chlorotoluene',
                '2-HEXANONE' : '2-Hexanone',
                '2-METHYLNAPHTHALENE' : '2-Methylnaphthalene',
                '2,2-DICHLOROPROPANE' : '2,2-Dichloropropane',
                '4-CHLOROTOLUENE' : '4-Chlorotoluene',
                '4-METHYL-2-PENTANONE' : '4-Methyl-2-Pentanone',
                '4-METHYL-2-PENTANONE (MIBK)' : '4-Methyl-2-Pentanone',
                'ACENAPHTHENE' : 'Acenaphthene',
                'ACENAPHTHYLENE' : 'Acenaphthylene',
                'ACETONE' : 'Acetone',
                'ACRYLONITRILE' : 'Acrylonitrile',
                'ALKALINITY, BICARBONATE' : 'Alkalinity Bicarb',
                'ALKALINITY, TOTAL' : 'Alkalinity Total',
                'ALUMINUM, TOTAL' : 'Aluminum',
                'AMMONIA AS NITROGEN': 'Ammonia',
                'ANTHRACENE' : 'Anthracene',
                'ANTIMONY, TOTAL': 'Antimony',
                'ARSENIC' : 'Arsenic',
                'ARSENIC, TOTAL': 'Arsenic',
                'BARIUM, TOTAL' : 'Barium',
                'BENZENE' : 'Benzene',
                'BENZO(A)ANTHRACENE' : 'Benzo(a)anthracene',
                'BENZO(A)PYRENE' : 'Benzo(a)pyrene',
                'BENZO(B)FLUORANTHENE' : 'Benzo(b)fluoranthene',
                'BENZO(GHI)PERYLENE' : 'Benzo(g,h,i)perylene',
                'BENZO(K)FLUORANTHENE' : 'Benzo(k)fluoranthene',
                'BERYLLIUM, TOTAL' : 'Beryllium',
                'BORON' : 'Boron',
                'BROMIDE' : 'Bromide',
                'BROMOBENZENE' : 'Bromobenzene',
                'BROMOCHLOROMETHANE' : 'Bromochloromethane',
                'BROMODICHLOROMETHANE' : 'Bromodichloromethane',
                'BROMOFORM' : 'Bromoform',
                'BROMOMETHANE' : 'Bromomethane',
                'C5-C8 ALIPHATICS, ADJUSTED' : 'C5-C8 Aliphatics, Adjusted',
                'C5-C8 ALIPHATICS' : 'C5-C8 Aliphatics', # not adjusted 
                'C9-C10 AROMATICS' : 'C9-C10 Aromatics',
                'C9-C12 ALIPHATICS, ADJUSTED' : 'C9-C12 Aliphatics, Adjusted',
                'C9-C12 ALIPHATICS' : 'C9-C12 Aliphatics', # not adjusted 
                'C9-C18 ALIPHATICS' : 'C9-C18 Aliphatics',
                'C11-C22 AROMATICS, ADJUSTED' : 'C11-C22 Aromatics, Adjusted',
                'C19-C36 ALIPHATICS' : 'C19-C36 Aliphatics',
                'CADMIUM, TOTAL' : 'Cadmium',
                'CALCIUM' : 'Calcium',
                'CALCIUM, TOTAL' : 'Calcium',
                'CARBON DISULFIDE' : 'Carbon Disulfide',
                'CARBON TETRACHLORIDE' : 'Carbon Tetrachloride',
                'CHEMICAL OXYGEN DEMAND' : 'Chemical Oxygen Demand',
                'CHLORIDE' : 'Chloride',
                'CHLOROBENZENE' : 'Chlorobenzene',
                'CHLOROETHANE' : 'Chloroethane',
                'CHLOROFORM' : 'Chloroform',
                'CHLOROMETHANE' : 'Chloromethane',
                'CHROMIUM, HEXAVALENT' : 'Chromium Hex',
                'CHROMIUM, TOTAL' : 'Chromium',
                'CHRYSENE' : 'Chrysene',
                'CIS 1,3-DICHLOROPROPENE' : '1,3-Dichloropropene',
                'CIS-1,3-DICHLOROPROPENE' : '1,3-Dichloropropene',
                'CIS-1,2-DICHLOROETHENE' : 'Cis-1,2-Dichloroethene',
                'COBALT, TOTAL' : 'Cobalt',
                'COLIFORM, TOTAL': 'Coliform',
                'COPPER' : 'Copper',
                'COPPER, TOTAL' : 'Copper',
                'DIBENZO(A,H)ANTHRACENE' : 'Dibenzo(a,h)anthracene',
                'DIBROMOCHLOROMETHANE' : 'Dibromochloromethane',
                'DIBROMOMETHANE' : 'Dibromomethane',
                'DICHLORODIFLUOROMETHANE' : 'Dichlorodifluoromethane',
                'DIETHYL ETHER' : 'Diethyl Ether',
                'DISSOLVED OXYGEN' : 'Dissolved Oxygen',
                'E. COLI BACTERIA' : 'Ecoli',
                'ESCHERICHIA COLI' : 'Ecoli',
                'ETHYL ETHER' : 'Ethyl Ether',
                'ETHYL METHACRYLATE' : 'Ethyl Methacrylate',
                'ETHYLBENZENE' : 'Ethylbenzene',
                'FLUORANTHENE' : 'Fluoranthene',
                'FLUORENE' : 'Fluorene',
                'FLUORIDE' : 'Flouride',
                'HARDNESS' : 'Hardness',
                'HARDNESS AS CALCIUM CARBONATE' : 'Hardness',
                'HEXACHLOROBUTADIENE' : 'Hexachlorobutadiene',
                'INDENO(1,2,3-CD)PYRENE' :'Indeno(1,2,3-cd)Pyrene',
                'IRON' : 'Iron',
                'IRON, TOTAL' : 'Iron',
                'ISOPROPYL BENZENE' : 'Isopropylbenzene',
                'ISOPROPYLBENZENE' : 'Isopropylbenzene',
                'LEAD, TOTAL' : 'Lead',
                'LEAD' : 'Lead',
                'M,P-XYLENE' : 'p/m-Xylene',
                'MANGANESE' : 'Manganese',
                'MANGANESE, TOTAL' : 'Manganese',
                'MAGNESIUM' : 'Magnesium',
                'MAGNESIUM, TOTAL' : 'Magnesium',
                'MERCURY' : 'Mercury',
                'MERCURY, TOTAL': 'Mercury',
                'METHANE' : 'Methane',
                'METHYL BUTYL KETONE' : 'Methyl Butyl Ketone',
                'METHYL CYCLOHEXANE' : 'Methyl Cyclohexane',
                'METHYL TERT BUTYL ETHER' : 'Methyl tert butyl ether',
                'METHYL-TERT-BUTYL ETHER (MTBE)' : 'Methyl tert butyl ether',
                'METHYLENE CHLORIDE' : 'Methylene Chloride',
                'N-BUTYLBENZENE' : 'N-Butylbenzene',
                'N-PROPYLBENZENE' : 'N-Propylbenzene',
                'NAPHTHALENE' : 'Naphthalene',
                'NICKEL, TOTAL' : 'Nickel',
                'NITROGEN, AMMONIA as N' : 'Ammonia',
                'NITROGEN, NITRITE as N' : 'Nitrite',
                'NITROGEN, NITRATE as N' : 'Nitrate',
                'NITRATE AS N' : 'Nitrate',
                'NITRATE AS NITROGEN' : 'Nitrate',
                'NITRITE AS N' : 'Nitrite',
                'NITRITE AS NITROGEN' : 'Nitrite',
                'NITRATE + NITRITE AS NITROGEN': 'Nitrogen',
                'O-CHLOROTOLUENE' : 'o-Chlorotoluene',
                'O-XYLENE' : 'o-Xylene',
                'P-CHLOROTOLUENE' : 'p-Chlorotoluene',
                'P-ISOPROPYLTOLUENE' : 'p-Isopropyltoluene',
                'P/M-XYLENE' : 'p/m-Xylene',
                'PH' : 'pH',
                'PHENANTHRENE' : 'Phenanthrene',
                'POTASSIUM' : 'Potassium',
                'POTASSIUM, TOTAL' : 'Potassium',
                'PYRENE' : 'Pyrene',
                'RADON' : 'Radon',
                'SELENIUM, TOTAL' : 'Selenium',
                'SEC-BUTYLBENZENE' : 'Sec-Butylbenzene',
                'SILVER, TOTAL': 'Silver',
                'SPECIFIC CONDUCTANCE': 'Specific Conductance',
                'SODIUM' : 'Sodium',
                'SODIUM, TOTAL' : 'Sodium',
                'SOLIDS, TOTAL DISSOLVED': 'Dissolved Solids',
                'SOLIDS, TOTAL': 'Solids', #soils
                'STYRENE' : 'Styrene',
                'SULFATE' : 'Sulfate',
                'TEMPERATURE': 'Temperature',
                'TERT-BUTYLBENZENE' : 'Tert-Butylbenzene',
                'TETRACHLOROETHENE' : 'Tetrachloroethene',
                'TETRACHLOROETHYLENE' : 'Tetrachloroethylene',
                'TETRAHYDROFURAN' : 'Tetrahydrofuran',
                'THALLIUM, TOTAL' :'Thallium',
                'TOLUENE' : 'Toluene',
                'TOTAL ALKALINITY' : 'Alkalinity total',
                'TOTAL COLIFORM BACTERIA' : 'Coliform',
                'TOTAL DISSOLVED SOLIDS': 'Dissolved Solids',
                'TOTAL HARDNESS' : 'Hardness',
                'TOTAL ORGANIC CARBON': 'Total Organic Carbon',
                'TOTAL URANIUM' : 'Uranium',
                'TRANS-1,2-DICHLOROETHENE' : 'Dichloroethene',
                'TRANS-1,3-DICHLOROPROPENE' : 'Dichloropropene',
                'TRANS-1,4-DICHLORO-2-BUTENE' : 'Trans-1,4-Dichloro-2-Butene',
                'TRICHLOROETHENE' : 'Trichloroethene',
                'TRICHLOROETHYLENE' : 'Trichloroethylene',
                'TRICHLOROFLUOROMETHANE' : 'Trichlorofluoromethane',
                'TURBIDITY' : 'Turbidity',
                'URANIUM-238' : 'Uranium',
                'URANIUM'  : 'Uranium',
                'URANIUM, CALC' : 'Uranium Calculated',
                'VANADIUM, TOTAL' : 'Vanadium',
                'VINYL ACETATE' : 'Vinyl Acetate',
                'VINYL CHLORIDE' : 'Vinyl Chloride',
                'XYLENE (TOTAL)' : 'Xylene Total',
                'ZINC, TOTAL' : 'Zinc',  
                '4,8-DIOXA-3H-PERFLUORONONANOIC ACID (ADONA)' :    'ADONA',
                '4,8-DIOXA-3H-PERFLUORONONANOIC ACID':             'ADONA',
                '1H,1H,2H,2H-PERFLUOROHEXANESULFONIC ACID (4:2FTS)' :  '4:2FTS',
                '4:2-FLUOROTELOMER SULFONIC ACID' :                    '4:2FTS',
                '1H,1H,2H,2H-PERFLUOROOCTANESULFONIC ACID (6:2FTS)':   '6:2FTS',
                '6:2 FLUOROTELOMER SULFONIC ACID':                     '6:2FTS',
                '1H,1H,2H,2H-PERFLUORODECANESULFONIC ACID (8:2FTS)':   '8:2FTS',
                '8:2 FLUOROTELOMER SULFONIC ACID':                     '8:2FTS',
                '2,3,3,3-TETRAFLUORO-2-[1,1,2,2,3,3,3-HEPTAFLUOROPROPOXY]-PROPANOIC ACID (HFPO-DA)':   'HFPO-DA' ,
                'HEXAFLUOROPROPYLENE OXIDE DIMER ACID':                                                'HFPO-DA' ,
                'N-ETHYL PERFLUOROOCTANESULFONAMIDOACETIC ACID (NETFOSAA)':    'NETFOSAA',
                'N-ETHYL PERFLUOROOCTANE SULFONAMIDOACETIC ACID':              'NETFOSAA',
                'N-METHYL PERFLUOROOCTANESULFONAMIDOACETIC ACID (NMEFOSAA)':   'NMEFOSAA',
                'N-METHYL PERFLUOROOCTANE SULFONAMIDOACETIC ACID':             'NMEFOSAA',
                'PERFLUOROBUTANESULFONIC ACID (PFBS)':                         'PFBS',
                'PERFLUOROBUTANE SULFONIC ACID':                               'PFBS',
                'PERFLUOROBUTANOIC ACID (PFBA)':   'PFBA',
                'PERFLUOROBUTANOIC ACID':          'PFBA',
                'PERFLUORODECANESULFONIC ACID (PFDS)': 'PFDS',
                'PERFLUORODECANESULFONIC ACID':        'PFDS',
                'PERFLUORODECANOIC ACID (PFDA)':   'PFDA',
                'PERFLUORODECANOIC ACID':          'PFDA',
                'PERFLUORODODECANOIC ACID (PFDOA)':    'PFDOA',
                'PERFLUORODODECANOIC ACID':            'PFDOA',
                'PERFLUOROHEPTANESULFONIC ACID (PFHPS)':   'PFHPS',
                'PERFLUOROHEPTANE SULFONIC ACID':          'PFHPS',
                'PERFLUOROHEPTANOIC ACID (PFHPA)': 'PFHPA',
                'PERFLUOROHEPTANOIC ACID':         'PFHPA',
                'PERFLUOROHEXADECANOIC ACID (PFHXDA)': 'PFHXDA',
                'PERFLUOROHEXADECANOIC ACID':          'PFHXDA',
                'PERFLUOROHEXANESULFONIC ACID (PFHXS)':    'PFHXS',
                'PERFLUOROHEXANE SULFONIC ACID':           'PFHXS',
                'PERFLUOROHEXANOIC ACID (PFHXA)':  'PFHXA',
                'PERFLUOROHEXANOIC ACID':          'PFHXA',
                'PERFLUORONONANESULFONIC ACID (PFNS)': 'PFNS',
                'PERFLUORONONANE SULFONIC ACID':       'PFNS',
                'PERFLUORONONANOIC ACID (PFNA)':   'PFNA',
                'PERFLUORONONANOIC ACID':          'PFNA',
                'PERFLUOROOCTADECANOIC ACID (PFODA)':  'PFODA',
                'PERFLUOROOCTADECANOIC ACID':          'PFODA',
                'PERFLUOROOCTANESULFONAMIDE (FOSA)':   'FOSA',
                'PERFLUOROOCTANE SULFONAMIDE':         'FOSA',
                'PERFLUOROOCTANESULFONIC ACID (PFOS)': 'PFOS',
                'PERFLUOROOCTANE SULFONIC ACID':       'PFOS',
                'PERFLUOROOCTANOIC ACID (PFOA)':   'PFOA',
                'PERFLUOROOCTANOIC ACID':          'PFOA',
                'PERFLUOROPENTANESULFONIC ACID (PFPES)':   'PFPES',
                'PERFLUOROPENTANE SULFONIC ACID':          'PFPES',
                'PERFLUOROPENTANOIC ACID (PFPEA)':     'PFPEA',
                'PERFLUOROPENTANOIC ACID':             'PFPEA',
                'PERFLUOROTETRADECANOIC ACID (PFTA)':  'PFTA',
                'PERFLUOROTETRADECANOIC ACID':         'PFTA',
                'PERFLUOROTRIDECANOIC ACID (PFTRDA)':  'PFTRDA',
                'PERFLUOROTRIDECANOIC ACID':           'PFTRDA',
                'PERFLUOROUNDECANOIC ACID (PFUNA)':    'PFUNA',
                'PERFLUOROUNDECANOIC ACID':            'PFUNA',
                'PFAS, TOTAL (6)':                                             'Sum of 6',
                'SUM OF 6 PFAS (PFHPA + PFHXS + PFOA + PFNA + PFOS + PFDA)':   'Sum of 6',
            }