# -*- coding: utf-8 -*-
"""
Created on Tue Apr  7 15:51:07 2026

@author: Lucas.Beem
"""
import numpy as np


#The keys in gw should match the output from edd_compounds.edd_compound
gw      = { '1,1-Dichloroethane' : '28',
            '1,1-Dichloroethene' : '290',
            '1,1-Dichloroethylene' : '28',
            '1,1-Dichloropropene' : '-',
            '1,1,1-Trichloroethane' : '8000',
            '1,1,1,2-Tetrachloroethane' : '5.7',
            '1,1,2-Trichloroethane' : '0.42',
            '1,1,2,2-Tetrachloroethane' : '0.76',
            '1,2-Dibromo-3-Chloropropane' : '0.0033',
            '1,2-Dibromoethane' : '0.075',
            '1,2-Dichlorobenzene' : '300',
            '1,2-Dichloroethane' : '1.7',
            '1,2-Dichloroethene' : '-',
            '1,2-Dichloropropane' : '8.3',
            '1,2,3-Trichlorobenzene' : '7',
            '1,2,3-Trichloropropane' : '0.0075',
            '1,2,4-Trichlorobenzene' : '4',
            '1,2,4-Trimethylbenzene' : '56',
            '1,2,4,5-Tetramethylbenzene' : '0.17',
            '1,3-Dichlorobenzene' : '300',
            '1,3-Dichloropropane' : '370',
            '1,3-Dichloropropene' : '4.7',
            '1,3,5-Trimethylbenzene' : '60',
            '1,4-Dichlorobenzene' : '4.8',
            '1,4-Dichlorobutane' : '0.013',
            '2-Butanone': '5600',
            '2-Chlorotoluene' : '-',
            '2-Hexanone' : '38',
            '2-Methylnaphthalene' : '36',
            '2,2-Dichloropropane' : '-',
            '4-Chlorotoluene' : '-',
            '4-Methyl-2-Pentanone': '6300',
            'Acetone' : '18000',
            'Acenaphthene' : '540',
            'Acenaphthylene' : '520',
            'Acrylonitrile': '0.52',
            'Aluminum' : '20000',
            'Alkalinity Bicarb' : '-',
            'Alkalinity Total' : '-',
            'Ammonia' : '-',
            'Anthracene' : '1800',
            'Antimony' : '7.8',
            'Arsenic' : '0.00052', #ppm
            'Barium' : '3800',
            'Benzene' : '4.6',
            'Benzo(a)anthracene' : '0.3',
            'Benzo(a)pyrene' : '0.25',
            'Benzo(b)fluoranthene' : '2.5',
            'Benzo(g,h,i)perylene' : '600',
            'Benzo(k)fluoranthene' : '25',
            'Beryllium' : '25',
            'Boron' : '4',  # ppm
            'Bromide' : '-',
            'Bromobenzene' : '62',
            'Bromochloromethane' : '83',
            'Bromodichloromethane' : '1.3',
            'Bromoform' : '33',
            'Bromomethane' : '7.6',
            'C5-C8 Aliphatics, Adjusted' : '180',
            'C5-C8 Aliphatics' : '-',
            'C9-C10 Aromatics' : '71',
            'C9-C12 Aliphatics, Adjusted' : '350',
            'C9-C12 Aliphatics' : '-',
            'C9-C18 Aliphatics' : '350',
            'C11-C22 Aromatics, Adjusted' : '600',
            'C19-C36 Aliphatics' : '40000',
            'Cadmium' : '1.8',
            'Calcium' : '-',
            'Carbon Disulfide' : '810',
            'Carbon Tetrachloride' : '4.6',
            'Chemical Oxygen Demand' : '-',
            'Chloride' : '-',
            'Chlorobenzene' : '78',
            'Chloroethane' : '-',
            'Chloroform' : '2.2',
            'Chloromethane' : '190',
            'Chromium' : '23000',
            'Chromium Hex' : '0.35',
            'Chrysene' : '250',
            'Cis-1,2-Dichloroethene' : '25',
            'Cobalt' : '6',
            'Coliform' : '-',
            'Copper' : '.8', # ppm
            'Dibenzo(a,h)anthracene' : '0.25',
            'Dibromochloromethane' : '8.7',
            'Dibromomethane' : '8.3',
            'Dichlorodifluoromethane' : '200',
            'Dichloroethene' : '-',
            'Dichloropropene' : '4.7',
            'Dissolved Oxygen' : '-',
            'Dissolved Solids' : '-',
            'Ecoli' : '-',
            'Ethylbenzene' : '15',
            'Ethyl Ether' : '3900',
            'Ethyl Methacrylate': '630',
            'Fluoranthene' : '800',
            'Fluorene' : '290',
            'Flouride' : '800',
            'Hardness' : '-',
            'Hexachlorobutadiene' : '1.4',
            'Indeno(1,2,3-cd)Pyrene' : '2.5',
            'Iron' : '14', # ppm
            'Isopropylbenzene' : '-',
            'Lead' : '.001', # ppm
            'Manganese' : '0.43', # ppm
            'Magnesium' : '-',
            'Mercury' : '0.63',
            'Methane' : '-',
            'Methyl Cyclohexane': '-',
            'Methyl tert butyl ether' : '140',
            'Methylene Chloride' : '110',
            'N-Butylbenzene' : '1000',
            'N-Propylbenzene' : '660',
            'Naphthalene' : '1.2',
            'Nickel' : '390',
            'Nitrate' : '32000',
            'Nitrite' : '2000',
            'o-Chlorotoluene': '240',
            'ORP': '-',
            'o-Xylene' : '190',
            'p-Chlorotoluene': '250',
            'p-Isopropyltoluene' : '-',
            'p/m-Xylene' : '190',
            'pH' : '-',
            'Phenanthrene' : '180',
            'Potassium' : '-',
            'Pyrene' : '120',
            'Radon' : '-',
            'Selenium' : '100',
            'Sec-Butylbenzene' : '2000',
            'Silver' : '94',
            'Specific Conductance' : '500', # screening level
            'Sodium' : '-',
            'Solids' : '-',
            'Styrene' : '1200',
            'Sulfate' : '-',
            'Temperature' : '-',
            'Tert-Butylbenzene' : '690',
            'Tetrachloroethene': '-',
            'Tetrachloroethylene' : '41',  
            'Tetrahydrofuran' : '3400',
            'Trichloroethene':'-',
            'Thallium' : '0.2',
            'Toluene' : '1100',
            'Trans-1,4-Dichloro-2-Butene': '0.013',
            'Total Organic Carbon' : '-',
            'Trichloroethylene' : '2.8',
            'Trichlorofluoromethane' : '5200',
            'Turbidity' : '-',
            'Uranium' : '-',
            'Uranium Calculated' : '-',
            'Vanadium' : '86',
            'Vinyl Acetate': '410',
            'Vinyl Chloride' : '0.19',
            'Xylene Total': '190',
            'Zinc' : '6000', }

pfas_gw = {'PFBS' : '6000',
              'PFBA': '19000',
              'PFHXS': '390',
              'PFHXA': '9900',
              'PFNA': '59',
              'PFOS' : '40',
              'PFOA' : '60',
              'Sum of 6': '20',
              'HFPO-DA':'-',
               '4:2FTS':'-',
               'PFPEA': '-',
               'PFPES': '-',
               'PFHXDA': '-',
               '6:2FTS':'-',
               'PFHPS': '-',
               'PFHPA': '-',
               'ADONA': '-',
               'NMEFOSAA':'-',
               'FOSA':'-',
               'NETFOSAA' : '-',
               '8:2FTS':'-',
               'PFNS':'-',
               'PFDA':'-',
               'PFDS':'-',
               'PFUNA': '-',
               'PFDOA': '-',
              'PFTRDA': '-',
              'PFTA': '-',
              'PFODA': '-',}

all_gw = gw | pfas_gw

# soil rags for petrolum in (ppm)
petrol_soil_leach = {'C9-C18 Aliphatics' : '26000',
            'C5-C8 Aliphatics, Adjusted' : '92',
            'C9-C12 Aliphatics, Adjusted' : '5800',
            'Benzene' : '4.6',
            'Toluene' : '1100',
            'Ethylbenzene' : '15',
            'p/m-Xylene' : '190',
            'o-Xylene' : '190',
            'Methyl tert butyl ether' : '140',
            'C9-C10 Aromatics' : '15',
            'C19-C36 Aliphatics' : '-',
            'C11-C22 Aromatics, Adjusted' : '340',
            'Naphthalene' : '0.21',
            '2-Methylnaphthalene' : '10',
            'Acenaphthylene' : '290',
            'Acenaphthene' : '300',
            'Fluorene' : '300',
            'Phenanthrene' : '320',
            'Anthracene' : '3200',
            'Fluoranthene' : '4900',
            'Pyrene' : '720',
            'Benzo(a)anthracene' : '5.8',
            'Chrysene' : '5000',
            'Benzo(b)fluoranthene' : '170',
            'Benzo(k)fluoranthene' : '1600',
            'Benzo(a)pyrene' : '16',
            'Indeno(1,2,3-cd)Pyrene' : '540',
            'Dibenzo(a,h)anthracene' : '53',
            'Benzo(g,h,i)perylene' : '100000',
            }

pfas_soil_leach = {'PFBS' : '110',
              'PFBA': '36',
              'PFHXS': '0.47',
              'PFHXA': '13',
              'PFNA': '4.6',
              'PFOS' : '1',
              'PFOA' : '17',
              'Sum of 6': '-',
              'HFPO-DA':'0.81',
               '4:2FTS':'-',
               'PFPEA': '-',
               'PFPES': '-',
               'PFHXDA': '-',
               '6:2FTS':'-',
               'PFHPS': '-',
               'PFHPA': '-',
               'ADONA': '-',
               'NMEFOSAA':'-',
               'FOSA':'-',
               'NETFOSAA' : '-',
               '8:2FTS':'-',
               'PFNS':'-',
               'PFDA':'-',
               'PFDS':'-',
               'PFUNA': '-',
               'PFDOA': '-',
              'PFTRDA': '-',
              'PFTA': '-',
              'PFODA': '-',}

all_ltg = petrol_soil_leach | pfas_soil_leach 



pfas_soil_resd = {'PFBS' : '26000',
              'PFBA': '110000',
              'PFHXS': '1700',
              'PFHXA': '43000',
              'PFNA': '260',
              'PFOS' : '170',
              'PFOA' : '260',
              'Sum of 6': '-',
              'HFPO-DA':'320',
               '4:2FTS':'-',
               'PFPEA': '-',
               'PFPES': '-',
               'PFHXDA': '-',
               '6:2FTS':'-',
               'PFHPS': '-',
               'PFHPA': '-',
               'ADONA': '-',
               'NMEFOSAA':'-',
               'FOSA':'-',
               'NETFOSAA' : '-',
               '8:2FTS':'-',
               'PFNS':'-',
               'PFDA':'-',
               'PFDS':'-',
               'PFUNA': '-',
               'PFDOA': '-',
              'PFTRDA': '-',
              'PFTA': '-',
              'PFODA': '-',}


petrol_soil_resd = {'2-Methylnaphthalene':'330',
                    'Acenaphthene': '4900',
                    'Acenaphthylene': '4900',
                    'Anthracene': '25000',
                    'Benzene': '17',
                    'Benzo(a)anthracene': '16',
                    'Benzo(a)pyrene':'1.6',
                    'Benzo(b)fluoranthene': '16', 
                    'Benzo(g,h,i)perylene': '2500',
                    'Benzo(k)fluoranthene': '160',
                    'C11-C22 Aromatics, Adjusted':'2600',
                    'C19-C36 Aliphatics': '100000',
                    'C5-C8 Aliphatics, Adjusted':'1700',
                    'C9-C10 Aromatics':'660',
                    'C9-C12 Aliphatics, Adjusted':'2500',
                    'C9-C18 Aliphatics':'2500',
                    'Chrysene':'1600',
                    'Dibenzo(a,h)anthracene':'1.6',
                    'Ethylbenzene':'86',
                    'Fluoranthene': '3300',
                    'Fluorene':'3300',
                    'Indeno(1,2,3-cd)Pyrene':'16',
                    'Methyl tert butyl ether':'690',
                    'Naphthalene':'29',
                    'Phenanthrene':'2500',
                    'Pyrene':'2500',
                    'Toluene':'750',
                    'o-Xylene':'260',
                    'p/m-Xylene':'260',
                    
                     
                    }

all_soil_resd = pfas_soil_resd | petrol_soil_resd



# reporting limit (ppt for PFAS; ppb for all else )
rl = {'PFBS' : '1.92',
              'PFBA': '1.92',
              'PFHXS': '1.92',
              'PFHXA': '1.92',
              'PFNA': '1.92',
              'PFOS' : '1.92',
              'PFOA' : '1.92',
              'Sum of 6': '-',
              'HFPO-DA':'19.2',
               '4:2FTS':'1.92',
               'PFPEA': '1.92',
               'PFPES': '1.92',
               'PFHXDA': '3.84',
               '6:2FTS':'1.92',
               'PFHPS': '1.92',
               'PFHPA': '1.92',
               'ADONA': '1.92',
               'NMEFOSAA':'1.92',
               'FOSA':'1.92',
               'NETFOSAA' : '1.92',
               '8:2FTS':'1.92',
               'PFNS':'1.92',
               'PFDA':'1.92',
               'PFDS':'1.92',
               'PFUNA': '1.92',
               'PFDOA': '3.84',
              'PFTRDA': '1.92',
              'PFTA': '1.92',
              'PFODA': '1.92',
              '1,1-Dichloroethane' : '-',
            '1,1-Dichloroethylene' : '-',
            '1,1-Dichloropropene' : '-',
            '1,1,1-Trichloroethane' : '-',
            '1,1,1,2-Tetrachloroethane' : '-',
            '1,1,2-Trichloroethane' : '-',
            '1,1,2,2-Tetrachloroethane' : '-',
            '1,2-Dibromo-3-Chloropropane' : '-',
            '1,2-Dibromoethane' : '-',
            '1,2-Dichlorobenzene' : '-',
            '1,2-Dichloroethane' : '-',
            '1,2-Dichloropropane' : '-',
            '1,2,3-Trichlorobenzene' : '-',
            '1,2,3-Trichloropropane' : '-',
            '1,2,4-Trichlorobenzene' : '-',
            '1,2,4-Trimethylbenzene' : '-',
            '1,3-Dichlorobenzene' : '-',
            '1,3-Dichloropropane' : '-',
            '1,3,5-Trimethylbenzene' : '-',
            '1,4-Dichlorobenzene' : '-',
            '2-Chlorotoluene' : '-',
            '2-Methylnaphthalene' : '0.4',
            '2,2-Dichloropropane' : '-',
            '4-Chlorotoluene' : '-',
            'Acenaphthene' : '0.4',
            'Acenaphthylene' : '0.4',
            'Aluminum' : '-',
            'Alkalinity Total' : '-',
            'Ammonia as Nitrogen' : '-',
            'Anthracene' : '0.4',
            'Antimony' : '-',
            'Arsenic' : '-',
            'Barium' : '-',
            'Benzene' : '-',
            'Benzo(a)anthracene' : '0.4',
            'Benzo(a)pyrene' : '0.2',
            'Benzo(b)fluoranthene' : '0.4',
            'Benzo(g,h,i)perylene' : '0.4',
            'Benzo(k)fluoranthene' : '0.4',
            'Beryllium' : '-',
            'Boron' : '-',
            'Bromide' : '-',
            'Bromobenzene' : '-',
            'Bromochloromethane' : '-',
            'Bromodichloromethane' : '-',
            'Bromoform' : '-',
            'Bromomethane' : '-',
            'C5-C8 Aliphatics, Adjusted' : '-',
            'C9-C10 Aromatics' : '-',
            'C9-C12 Aliphatics, Adjusted' : '-',
            'C9-C18 Aliphatics' : '100',
            'C11-C22 Aromatics, Adjusted' : '100',
            'C19-C36 Aliphatics' : '100',
            'Cadmium' : '-',
            'Calcium' : '-',
            'Carbon Disulfide' : '-',
            'Carbon Tetrachloride' : '-',
            'Chloride' : '-',
            'Chlorobenzene' : '-',
            'Chloroethane' : '-',
            'Chloroform' : '-',
            'Chloromethane' : '-',
            'Chromium' : '-',
            'Chrysene' : '-',
            'Cis-1,2-Dichloroethene' : '-',
            'Cobalt' : '-',
            'Copper' : '-',
            'Dibenzo(a,h)anthracene' : '0.4',
            'Dibromochloromethane' : '-',
            'Dibromomethane' : '-',
            'Dichlorodifluoromethane' : '-',
            'Dissolved Oxygen' : '-',
            'Dissolved Solids' : '-',
            'Ecoli' : '-',
            'Ethylbenzene' : '-',
            'Fluoranthene' : '0.4',
            'Fluorene' : '0.4',
            'Flouride' : '-',
            'Hexachlorobutadiene' : '-',
            'Indeno(1,2,3-cd)Pyrene' : '0.4',
            'Iron' : '-',
            'Isopropyl Benzene' : '-',
            'Lead' : '-',
            'Manganese' : '-',
            'Magnesium' : '-',
            'Mercury' : '-',
            'Methyl tert butyl ether' : '-',
            'Methylene Chloride' : '-',
            'N-Butylbenzene' : '-',
            'N-Propylbenzene' : '-',
            'Naphthalene' : '0.4',
            'Nickel' : '-',
            'Nitrate' : '-',
            'Nitrite' : '-',
            'o-Xylene' : '-',
            'P-Isopropyltoluene' : '-',
            'p/m-Xylene' : '-',
            'pH' : '-',
            'Phenanthrene' : '0.4',
            'Potassium' : '-',
            'Pyrene' : '0.4',
            'Radon' : '-',
            'Selenium' : '-',
            'Sec-Butylbenzene' : '-',
            'Silver' : '-',
            'Specific Conductance' : '-',
            'Sodium' : '-',
            'Styrene' : '-',
            'Sulfate' : '-',
            'Temperature' : '-',
            'Tert-Butylbenzene' : '-',
            'Tetrachloroethylene' : '-',
            'Thallium' : '-',
            'Toluene' : '-',
            'Alkalinity' : '-',
            'Coliform' : '-',
            'Hardness' : '-',
            'Total Organic Carbon' : '-',
            'Uranium' : '-',
            'Trichloroethylene' : '-',
            'Trichlorofluoromethane' : '-',
            'Turbidity' : '-',
            'Vanadium' : '-',
            'Vinyl Chloride' : '-',
            'Zinc' : '-', }

# mimimum detection limit (ppt for PFAS; ppb for all else )
mdl = { 'PFBS' : '0.245',
              'PFBA': '0.421',
              'PFHXS': '0.388',
              'PFHXA': '0.338',
              'PFNA': '0.322',
              'PFOS' : '0.520',
              'PFOA' : '0.243',
              'Sum of 6': '-',
              'HFPO-DA':'14.6',
               '4:2FTS':'0.466',
               'PFPEA': '0.408',
               'PFPES': '0.253',
               'PFHXDA': '1.28',
               '6:2FTS':'1.37',
               'PFHPS': '0.709',
               'PFHPA': '0.232',
               'ADONA': '0.346',
               'NMEFOSAA':'0.668',
               'FOSA':'0.598',
               'NETFOSAA' : '0.829',
               '8:2FTS':'1.25',
               'PFNS':'1.15',
               'PFDA':'0.313',
               'PFDS':'1.01',
               'PFUNA': '0.268',
               'PFDOA': '0.384',
              'PFTRDA': '0.337',
              'PFTA': '0.256',
              'PFODA': '1.18',
              '1,1-Dichloroethane' : '-',
            '1,1-Dichloroethylene' : '-',
            '1,1-Dichloropropene' : '-',
            '1,1,1-Trichloroethane' : '-',
            '1,1,1,2-Tetrachloroethane' : '-',
            '1,1,2-Trichloroethane' : '-',
            '1,1,2,2-Tetrachloroethane' : '-',
            '1,2-Dibromo-3-Chloropropane' : '-',
            '1,2-Dibromoethane' : '-',
            '1,2-Dichlorobenzene' : '-',
            '1,2-Dichloroethane' : '-',
            '1,2-Dichloropropane' : '-',
            '1,2,3-Trichlorobenzene' : '-',
            '1,2,3-Trichloropropane' : '-',
            '1,2,4-Trichlorobenzene' : '-',
            '1,2,4-Trimethylbenzene' : '-',
            '1,3-Dichlorobenzene' : '-',
            '1,3-Dichloropropane' : '-',
            '1,3,5-Trimethylbenzene' : '-',
            '1,4-Dichlorobenzene' : '-',
            '2-Chlorotoluene' : '-',
            '2-Methylnaphthalene' : '0.077',
            '2,2-Dichloropropane' : '-',
            '4-Chlorotoluene' : '-',
            'Acenaphthene' : '0.4',
            'Acenaphthylene' : '0.4',
            'Aluminum' : '-',
            'Alkalinity Total' : '-',
            'Ammonia as Nitrogen' : '-',
            'Anthracene' : '0.4',
            'Antimony' : '-',
            'Arsenic' : '-',
            'Barium' : '-',
            'Benzene' : '-',
            'Benzo(a)anthracene' : '0.088',
            'Benzo(a)pyrene' : '0.072',
            'Benzo(b)fluoranthene' : '0.102',
            'Benzo(g,h,i)perylene' : '0.102',
            'Benzo(k)fluoranthene' : '0.126',
            'Beryllium' : '-',
            'Boron' : '-',
            'Bromide' : '-',
            'Bromobenzene' : '-',
            'Bromochloromethane' : '-',
            'Bromodichloromethane' : '-',
            'Bromoform' : '-',
            'Bromomethane' : '-',
            'C5-C8 Aliphatics, Adjusted' : '-',
            'C9-C10 Aromatics' : '-',
            'C9-C12 Aliphatics, Adjusted' : '-',
            'C9-C18 Aliphatics' : '100',
            'C11-C22 Aromatics, Adjusted' : '100',
            'C19-C36 Aliphatics' : '100',
            'Cadmium' : '-',
            'Calcium' : '-',
            'Carbon Disulfide' : '-',
            'Carbon Tetrachloride' : '-',
            'Chloride' : '-',
            'Chlorobenzene' : '-',
            'Chloroethane' : '-',
            'Chloroform' : '-',
            'Chloromethane' : '-',
            'Chromium' : '-',
            'Chrysene' : '-',
            'Cis-1,2-Dichloroethene' : '-',
            'Cobalt' : '-',
            'Copper' : '-',
            'Dibenzo(a,h)anthracene' : '0.091',
            'Dibromochloromethane' : '-',
            'Dibromomethane' : '-',
            'Dichlorodifluoromethane' : '-',
            'Dissolved Oxygen' : '-',
            'Dissolved Solids' : '-',
            'Ecoli' : '-',
            'Ethylbenzene' : '-',
            'Fluoranthene' : '0.121',
            'Fluorene' : '0.097',
            'Flouride' : '-',
            'Hexachlorobutadiene' : '-',
            'Indeno(1,2,3-cd)Pyrene' : '0.095',
            'Iron' : '-',
            'Isopropyl Benzene' : '-',
            'Lead' : '-',
            'Manganese' : '-',
            'Magnesium' : '-',
            'Mercury' : '-',
            'Methyl tert butyl ether' : '-',
            'Methylene Chloride' : '-',
            'N-Butylbenzene' : '-',
            'N-Propylbenzene' : '-',
            'Naphthalene' : '0.136',
            'Nickel' : '-',
            'Nitrate' : '-',
            'Nitrite' : '-',
            'o-Xylene' : '-',
            'P-Isopropyltoluene' : '-',
            'p/m-Xylene' : '-',
            'pH' : '-',
            'Phenanthrene' : '0.084',
            'Potassium' : '-',
            'Pyrene' : '0.114',
            'Radon' : '-',
            'Selenium' : '-',
            'Sec-Butylbenzene' : '-',
            'Silver' : '-',
            'Specific Conductance' : '-',
            'Sodium' : '-',
            'Styrene' : '-',
            'Sulfate' : '-',
            'Temperature' : '-',
            'Tert-Butylbenzene' : '-',
            'Tetrachloroethylene' : '-',
            'Thallium' : '-',
            'Toluene' : '-',
            'Alkalinity' : '-',
            'Coliform' : '-',
            'Hardness' : '-',
            'Total Organic Carbon' : '-',
            'Uranium' : '-',
            'Trichloroethylene' : '-',
            'Trichlorofluoromethane' : '-',
            'Turbidity' : '-',
            'Vanadium' : '-',
            'Vinyl Chloride' : '-',
            'Zinc' : '-', }




test_compounds = {'landfill_short' :['Alkalinity Total',
                                          'Arsenic',
                                          'Calcium',
                                          'Chloride',
                                          'Iron',
                                          'Potassium',
                                          'Magnesium',
                                          'Manganese',
                                          'Sodium',
                                          'Ammonia',
                                          'Nitrate',
                                          'Sulfate',
                                          'Dissolved Solids',
                                          'Total Organic Carbon'],
                  
                    'landfill_long' : ['Methane',
                                        'Alkalinity Bicarb',
                                        'Alkalinity Total',
                                        'Arsenic',
                                        'Barium',
                                        'Bromide',
                                        'Calcium',
                                        'Cadmium',
                                        'Chloride',
                                        'Chemical Oxygen Demand',
                                        'Chromium',
                                        'Copper',
                                        'Iron',
                                        'Hardness',
                                        'Chromium Hex',
                                        'Mercury',
                                        'Potassium',
                                        'Magnesium',
                                        'Manganese',
                                        'Sodium',
                                        'Ammonia',
                                        'Nitrite',
                                        'Nitrate',
                                        'Lead',
                                        'Sulfate',
                                        'Dissolved Solids',
                                        'Total Organic Carbon'],

                    'voc' : [ '1,1,1,2-Tetrachloroethane',
                            '1,1,1-Trichloroethane',
                            '1,1,2,2-Tetrachloroethane',
                            '1,1,2-Trichloroethane',
                            '1,1-Dichloroethane',
                            '1,1-Dichloroethene',
                            '1,1-Dichloropropene',
                            '1,2,3-Trichlorobenzene',
                            '1,2,3-Trichloropropane',
                            '1,2,4,5-Tetramethylbenzene',
                            '1,2,4-Trichlorobenzene',
                            '1,2,4-Trimethylbenzene',
                            '1,2-Dibromo-3-Chloropropane',
                            '1,2-Dibromoethane',
                            '1,2-Dichlorobenzene',
                            '1,2-Dichloroethane',
                            '1,2-Dichloroethene',
                            '1,2-Dichloropropane',
                            '1,3,5-Trimethylbenzene',
                            '1,3-Dichlorobenzene',
                            '1,3-Dichloropropane',
                            '1,3-Dichloropropene',
                            '1,4-Dichlorobenzene',
                            '1,4-Dichlorobutane',
                            '2,2-Dichloropropane',
                            '2-Butanone',
                            '2-Hexanone',
                            '4-Methyl-2-Pentanone',
                            'Acetone',
                            'Acrylonitrile',
                            'Benzene',
                            'Bromobenzene',
                            'Bromochloromethane',
                            'Bromodichloromethane',
                            'Bromoform',
                            'Bromomethane',
                            'Carbon Disulfide',
                            'Carbon Tetrachloride',
                            'Chlorobenzene',
                            'Chloroethane',
                            'Chloroform',
                            'Chloromethane',
                            'Cis-1,2-Dichloroethene',
                            'Dibromochloromethane',
                            'Dibromomethane',
                            'Dichlorodifluoromethane',
                            'Ethyl Ether',
                            'Ethyl Methacrylate',
                            'Ethylbenzene',
                            'Hexachlorobutadiene',
                            'Isopropylbenzene',
                            'Methyl Cyclohexane',
                            'Methyl tert butyl ether',
                            'Methylene Chloride',
                            'N-Butylbenzene',
                            'N-Propylbenzene',
                            'Naphthalene',
                            'o-Chlorotoluene',
                            'o-Xylene',
                            'p-Chlorotoluene',
                            'p-Isopropyltoluene',
                            'p/m-Xylene',
                            'Sec-Butylbenzene',
                            'Styrene',
                            'Tert-Butylbenzene',
                            'Tetrachloroethene',
                            'Tetrahydrofuran',
                            'Toluene',
                            'Dichloroethene',
                            'Dichloropropene',
                            'Trans-1,4-Dichloro-2-Butene',
                            'Trichloroethene',
                            'Trichlorofluoromethane',
                            'Vinyl Acetate',
                            'Vinyl Chloride',
                            'Xylene Total',],

                    'pfas' : ['HFPO-DA',
                                  'PFBA' ,
                                  'PFBS',
                                  '4:2FTS',
                                  'PFPEA',
                                  'PFPES',
                                  'PFHXA',
                                  'PFHXS',
                                  'PFHXDA',
                                  'PFHPS',
                                  'PFHPA',
                                  'ADONA',
                                  'PFOS',
                                  'PFOA',
                                  'NMEFOSAA',
                                  'FOSA',
                                  'NETFOSAA',
                                  '6:2FTS',
                                  'PFNA',
                                  'PFNS',
                                  'PFDA',
                                  'PFDS',
                                  '8:2FTS',
                                  'PFUNA',
                                  'PFDOA',
                                  'PFTRDA',
                                  'PFTA',
                                  'PFODA',
                                  'Sum of 6'],

                        'pot' : ['Arsenic',
                                'Copper' ,
                                'Manganese',
                                'Uranium',
                                'Uranium Calculated',
                                'Nitrite' ,
                                'Nitrate',
                                'Radon',
                                'pH' ,
                                'Ecoli',
                                'Flouride',
                                'Chloride' ,
                                'Iron' ,
                                'Hardness' ,
                                'Calcium',
                                'Magnesium' ,
                                'Coliform'],
                        
                        'eph' : ['2-Methylnaphthalene',
                                'Acenaphthene',
                                'Acenaphthylene',
                                'Anthracene',
                                'Benzo(a)anthracene',
                                'Benzo(a)pyrene',
                                'Benzo(b)fluoranthene',
                                'Benzo(g,h,i)perylene',
                                'Benzo(k)fluoranthene',
                                'C11-C22 Aromatics, Adjusted',
                                'C19-C36 Aliphatics',
                                'C9-C18 Aliphatics',
                                'Chrysene',
                                'Dibenzo(a,h)anthracene',
                                'Fluoranthene',
                                'Fluorene',
                                'Indeno(1,2,3-cd)Pyrene',
                                'Naphthalene',
                                'Phenanthrene',
                                'Pyrene'],
                        

                        'vph' : ['C9-C10 Aromatics',
                               'C5-C8 Aliphatics, Adjusted',
                               'C9-C12 Aliphatics, Adjusted',
                               'Benzene',
                               'Toluene',
                               'Ethylbenzene',
                               'p/m-Xylene',
                               'o-Xylene',
                               'Methyl tert butyl ether',
                               'Naphthalene'],
                        
                        'field' : ['pH',
                                   'Dissolved Oxygen',
                                   'Specific Conductance',
                                   'Temperature',
                                   'Turbidity',
                                   'ORP'],
                                    }

#year 2023,2021,2018,2016,2013
# napthalene is only one that changed since 2018
historic_rag_gw = {'C9-C18 Aliphatics' : [350 , 350 , 350,700,700],
     'C5-C8 Aliphatics, Adjusted' : [180,180,180,300,300],
     'C9-C12 Aliphatics, Adjusted' : [350 , 350 , 350,700,700],
     'Benzene' : [4.6,4.6,4.6,4,4],
     'Toluene' : [1100,1100,1100,600,600],
     'Ethylbenzene' : [15,15,15,30,30],
     'p/m-Xylene' : [190,190,190,1000,1000],
     'o-Xylene' : [190,190,190,1000,1000],
     'Methyl tert butyl ether' : [140,140,140,40,40],
     'C9-C10 Aromatics' : [71,71,71,200,200],
     'C19-C36 Aliphatics' : [40000,40000,40000,10000,10000],
     'C11-C22 Aromatics, Adjusted' : [600,600,600,200,200],
     'Naphthalene' : [1.2,1.2,1.7,10,10],
     '2-Methylnaphthalene' : [36,36,36,30,30],
     'Acenaphthylene' : [520,520,520,np.nan,np.nan],
     'Acenaphthene' : [540,540,540,400,400],
     'Fluorene' : [290,290,290,300,300],
     'Phenanthrene' : [180,180,180,np.nan,np.nan],
     'Anthracene' : [1800,1800,1800,2000,2000],
     'Fluoranthene' : [800,800,800,300,300],
     'Pyrene' : [120,120,120,200,200],
     'Benzo(a)anthracene' : [0.3,0.3,0.3,0.5,0.5],
     'Chrysene' : [250,250,250,50,50],
     'Benzo(b)fluoranthene' : [2.5,2.5,2.5,0.5,0.5],
     'Benzo(k)fluoranthene' : [25,25,25,5,5],
     'Benzo(a)pyrene' : [0.25,0.25,0.25,0.05,0.05],
     'Indeno(1,2,3-cd)Pyrene' : [2.5,2.5,2.5,0.5,0.5],
     'Dibenzo(a,h)anthracene' : [0.25,0.25,0.25,0.05,0.05],
     'Benzo(g,h,i)perylene' : [600,600,600,np.nan,np.nan],
     }