# -*- coding: utf-8 -*-
"""
Created on Mon Apr 27 15:32:10 2026

@author: Lucas.Beem
"""

import os
import sys
base_folder = os.path.dirname(__file__) #folder that contains the script
sys.path.append(os.path.join(base_folder+'/lookup'))
import rags
import numpy as np
import matplotlib.pylab as pl 
# import parse_utils
# import paths
# import argparse


def get_max_cons(results):
    try:
        mm = np.array(results)[:,:,1]
        mm[mm == 'ND'] = 0
        cons = []
        for m in mm:
            for ms in m[:-1]:
                cons.append(float(ms))
    except:
        cons = []
        for resu in results:
            
            for re in resu:
                res_str = re[1]
                if res_str in ['ND','']:
                    cons.append(0)
                else:
                    cons.append(float(res_str))   
    return np.max(cons)

def general_compare_plot(typ,results,out,labels,save=True,show=True):
    # typ : type of plot (pfas,voc,landfill_short,landfill_long,vph,eph)
    # results list: generated by from edd_utils 
    # out: output folder 
    # labels: labels for each of the sample locations in results
    types = ['pfas','voc','landfill_short','landfill_long','vph','eph','pot']
    
    if typ not in types:
        print('refactor/plot_utils.general_compare_plot: Suppled plot type not found: {}'.format(typ))
        print('must be:')
        print(types)
        exit()
        
    
    # plot order
    order = rags.test_compounds[typ]

    style = [['.','tab:blue'],
             ['s','tab:orange'],
             ['^','tab:green'],
             ['+','tab:red'],
            ]

   # get max concentration 
    max_cons = get_max_cons(results)
    nd_plot = -max_cons/10
    
    
    if typ in ['voc']:
        fs = [15,9]
        ylabel_unit = '(ppb)'
    elif typ in ['landfill_long']:
        fs = [8.5,11]
        ylabel_unit = '(ppm)'
    elif typ in ['landfill_short']:
        fs = [6.4,7]
        ylabel_unit = '(ppm)'
    else:
        fs = None
        ylabel_unit = ' (ppb)'
    fig = pl.figure(figsize=fs)
    fig.clf()
    ax = pl.subplot(111)
    
    bbox = ax.get_position()
    bbox.y0 = 0.3
    bbox.y1 = 0.8
    ax.set_position(bbox)
    
    for i,resul in enumerate(results):

        res = np.array(resul)
        res[res == 'ND'] = nd_plot
        res[res == ''] = np.nan
        l = 0
        for j,ords in enumerate(order):
            I = np.nonzero(res == ords)
            
            if len(I[0]) > 0:
                I = int(I[0])
                if l == 0:
                    ax.plot(j,float(res[I][1]),color= style[i][1],marker=style[i][0],markerfacecolor='none',label=labels[i])
                    l += 1
                else:
                    ax.plot(j,float(res[I][1]),color= style[i][1],marker=style[i][0],markerfacecolor='none')
    if typ in ['pfas']:
        ax.set_ylabel('Concentration (ppt)',fontsize=12)
    else:
        ax.set_ylabel('Concentration '+ylabel_unit,fontsize=12)
    ax.set_xticks(np.arange(0,len(order)))
    ax.set_xticklabels(order,rotation=-90)
    ax.tick_params(axis='both', labelsize=12)
    
    # get y tick locations
    locs = ax.get_yticks()
    ax.set_yticks(locs[locs>=0])
    
    
    if typ == 'pfas':
        divider = [.5,3.5,5.5,9.5,12.5,18.5,20.5,22.5,23.5,24.5,25.5,26.5]
        chain_length = [3,4,5,6,7,8,9,10,11,12,13,14,18]
        ymin,ymax = ax.get_ylim()
        ax.vlines(divider,ymin,ymax,linewidth=.1,color='k')
        
        for div,leng in zip(divider,chain_length):
            ax.text(div,ymax,str(leng),va='center',ha='right',fontsize=6,color=[.7,.7,.7])
        ax.text(divider[-1],ymax,str(chain_length[-1]),va='center',ha='left',fontsize=6,color=[.7,.7,.7])
   
    xmin,xmax = ax.get_xlim()
    ax.hlines(0,xmin,xmax,linewidth=.1,color='k')
    
    ax.text(-.5,nd_plot,'ND',va='center',ha='right',fontsize=8)
    
    ax.legend(handlelength=0,bbox_to_anchor=(0., 1.02, 1., .102), loc='lower left',
                      ncols=len(labels), mode="expand", borderaxespad=0.,fontsize=12)
    fig_name = out +'/gen_compare.png'
    
    if save:
        fig.savefig(fig_name,dpi=200)
        print('saved file: {}'.format(fig_name))
    if show:
        os.startfile(fig_name)
    
    return fig